[project]
name = "fin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.2.3",
    "plotly>=5.17.0",
    "sqlmodel>=0.0.24",
    "streamlit>=1.45.1",
    "typer>=0.16.0",
    "watchdog>=6.0.0",
]
